import type { Testimonial } from '@/components/animated-testimonials'

export const testimonialsData: Testimonial[] = [
  { id: 1, content: 'Ya lo recibí linda, muchas gracias, está hermoso.', rating: 5 },
  { id: 2, content: 'Me encantó la camisa, súper linda. Pronto pido más.', rating: 5 },
  { id: 3, content: 'Están súper lindos, te agradezco muchísimo.', rating: 5 },
  { id: 4, content: 'Está precioso, muchas gracias y la atención de 10.', rating: 5 },
  { id: 5, content: 'Ya llegó, muy lindo. Muchas gracias.', rating: 5 },
  { id: 6, content: 'El set hermoso y la tela súper cómoda. Gracias.', rating: 5 },
  { id: 7, content: 'Muchas gracias, está súper lindo el short.', rating: 5 },
  { id: 8, content: 'Todo súper lindo, muchas gracias.', rating: 5 },
  { id: 9, content: 'Gracias por su amabilidad, soy clienta fija ya.', rating: 5 },
  { id: 10, content: 'Todo hermoso, muchas gracias.', rating: 5 },
  { id: 11, content: 'Ya lo recibí, están súper bonitos. Gracias.', rating: 5 },
  { id: 12, content: 'La calidad es excelente, se nota la tela.', rating: 5 },
  { id: 13, content: 'Llegó rapidísimo, quedé encantada.', rating: 5 },
  { id: 14, content: 'El color es tal cual la foto, hermoso.', rating: 5 },
  { id: 15, content: 'Mi esposo quedó feliz con la camisa.', rating: 5 },
  { id: 16, content: 'La talla perfecta, gracias por la asesoría.', rating: 5 },
  { id: 17, content: 'Segunda compra y sigue igual de bien.', rating: 5 },
  { id: 18, content: 'El empaque muy cuidado, se ve profesional.', rating: 5 },
  { id: 19, content: 'Recomendadísimos, ya les pasé el contacto.', rating: 5 },
  { id: 20, content: 'La tela fresca y cómoda, ideal para el calor.', rating: 5 },
  { id: 21, content: 'El pantalón quedó espectacular, gracias.', rating: 5 },
  { id: 22, content: 'Atención rápida por WhatsApp, 10 de 10.', rating: 5 },
  { id: 23, content: 'Compré para regalo y le encantó.', rating: 5 },
  { id: 24, content: 'Los colores vibrantes, tal como los pedí.', rating: 5 },
  { id: 25, content: 'Muy buena relación calidad-precio.', rating: 5 },
  { id: 26, content: 'El conjunto quedó divino, gracias TOPSTORE.', rating: 5 },
  { id: 27, content: 'Llegó antes de lo que pensaba, excelente.', rating: 5 },
  { id: 28, content: 'La costura impecable, se ve de calidad.', rating: 5 },
  { id: 29, content: 'Ya pedí otro color, me encantó el primero.', rating: 5 },
  { id: 30, content: 'Súper amables, resolvieron todas mis dudas.', rating: 5 },
  { id: 31, content: 'El vestido hermoso, me quedó perfecto.', rating: 5 },
  { id: 32, content: 'Buenísimo el short, cómodo y bonito.', rating: 5 },
  { id: 33, content: 'Mi hija quedó feliz, gracias por todo.', rating: 5 },
  { id: 34, content: 'La camiseta suave, no se encoge al lavar.', rating: 5 },
  { id: 35, content: 'Pedí dos tallas y me ayudaron a elegir bien.', rating: 5 },
  { id: 36, content: 'Todo llegó completo y bien empacado.', rating: 5 },
  { id: 37, content: 'El diseño único, no lo encuentro en otro lado.', rating: 5 },
  { id: 38, content: 'Muy satisfecha, volveré a comprar seguro.', rating: 5 },
  { id: 39, content: 'La blusa preciosa, la uso todo el tiempo.', rating: 5 },
  { id: 40, content: 'Gracias por la paciencia con mis preguntas.', rating: 5 },
  { id: 41, content: 'El buzo cómodo y abrigador, me encanta.', rating: 5 },
  { id: 42, content: 'Linda la colección, difícil elegir solo uno.', rating: 5 },
  { id: 43, content: 'Mi novio quedó guapísimo con el outfit.', rating: 5 },
  { id: 44, content: 'Entrega puntual, tal como lo prometieron.', rating: 5 },
  { id: 45, content: 'La falda quedó hermosa, gracias linda.', rating: 5 },
  { id: 46, content: 'Calidad premium, se nota en los detalles.', rating: 5 },
  { id: 47, content: 'Ya somos tres amigas comprando aquí.', rating: 5 },
  { id: 48, content: 'El overol divino, me quedó a la medida.', rating: 5 },
  { id: 49, content: 'Respuesta inmediata, muy buen servicio.', rating: 5 },
  { id: 50, content: 'Los accesorios combinan perfecto con la ropa.', rating: 5 },
  { id: 51, content: 'Pedí para mi mamá y quedó encantada.', rating: 5 },
  { id: 52, content: 'La tela no transparenta, muy buena calidad.', rating: 5 },
  { id: 53, content: 'El set de verano hermoso, fresquito.', rating: 5 },
  { id: 54, content: 'Confío totalmente, siempre cumplen.', rating: 5 },
  { id: 55, content: 'El pantaloncito quedó perfecto, gracias.', rating: 5 },
  { id: 56, content: 'Muy bonita la presentación del paquete.', rating: 5 },
  { id: 57, content: 'La camisa de lino fresca, ideal.', rating: 5 },
  { id: 58, content: 'Excelente asesoría de tallas, acertaron.', rating: 5 },
  { id: 59, content: 'Todo como en las fotos, sin sorpresas.', rating: 5 },
  { id: 60, content: 'Mi pedido favorito del año, gracias TOPSTORE.', rating: 5 },
]
